# Table of Contents

- [HIDBINIT](#step-1-hidbinit)
	* [hidbinit usage](#11-usage)
	* [hidbinit full example](#12-full-example)
- [DBDGEN](#step-2-dbdgen)
	* [dbdgen usage](#21-usage)
	* [dbdgen full example](#22-full-example)
- [HDGENSCH](#step-3-hdgensch)
	* [hdgensch usage](#31-usage)
	* [hdgensch full example](#32-full-example)
- [HIDBMGR](#step-4-hidbmgr)
	* [hidbmgr usage](#41-usage)
	* [hidbmgr full example](#42-full-example)
- [COMPILE](#step-5-compile)
	* [compile full example](#51-full-example)
- [HDPCDF01](#step-6-hdpcdf01)
	* [hdpcdf01 usage](#61-usage)
	* [hdpcdf01 full example](#62-full-example)
- [DSMIGIN](#step-7-dsmigin)
	* [dsmigin full example](#71-full-example)
- [HDLOAD](#step-8-hdload)
	* [hdload usage](#81-usage)
	* [hdload full example](#82-full-example)
